### ISSUE TITLE
[BUG] Decoding using flutter_theme throws cast error

### ISSUE THREAD

**Issue by pauli2406** [zeshuaro/flutter_theme#157]
**Platform**

MacOS / Flutter 2.5.3

**Steps To Reproduce**

1. Clone the example flutter project and start it in debug mode
2. Enable catching uncaught exceptions in VS Code

**Expected Behavior**

The theme should be decoded without throwing an exception.

**Actual behaviour**
The application waits when decoding the theme and throws an Cast Error exception:
"Null check operator used on a null value"

**Screenshots**
<img width="926" alt="image" src="https://user-images.githubusercontent.com/24795790/144688359-5fc36b53-1109-48e8-b942-f580e2d6954c.png">

<img width="1357" alt="image" src="https://user-images.githubusercontent.com/24795790/144688371-5b9e8d92-101c-4e85-8724-302582bc480d.png">

**Additional Context**

**Comment by zeshuaro** [comment]
@pauli2406 Thanks for reporting this issue. I've updated the example app and the issue should be fixed. Feel free to reopen this issue if not.

**Comment by zeshuaro** [comment]
This has been fixed on `json_theme` version 3.2.0. Flutter Theme has also been updated to use the latest version.

**Comment by pauli2406** [comment]
@zeshuaro Thanks for looking into it! Do I need to recreate my json theme file or should it work oob?

**Comment by zeshuaro** [comment]
I don't think you'll need to recreate your json theme file. If you use the latest version of `json_theme` then it should work without throwing the exception.
