### ISSUE TITLE
Input decoration theme UI is not working

### ISSUE THREAD

**Issue by suv12345** [zeshuaro/flutter_theme#166]
**Platform**

Web

**Steps To Reproduce**

1. Open link https://zeshuaro.github.io/flutter_theme/#/
2. Go to advanced tab
3. Change input decoration theme UI 

**Expected Behavior**
All reflected both in theme config UI as well as preview UI

**Actual behavior**

Nothing got reflected and no impact on changed theme in preview UI of inputs

**Comment by zeshuaro** [comment]
@suvdev123 Thanks for reporting the issue. Would you mind to clarify which options for input decoration are not being reflected on the UI?

Note that for input decoration, all the colour options have no effects unless the option `Filled` is turned on.

**Comment by suv12345** [comment]
> `Filled` is turned on.

Ok, There was a misunderstanding about this .  what about Focus Color of input decoration theme.

**Comment by zeshuaro** [comment]
Turns out `focusColor` doesn't seem to be used anymore in `InputDecoration`. See https://github.com/flutter/flutter/issues/50866.

I'll probably raise a PR to remove this in Flutter Theme to avoid confusions.

**Comment by suv12345** [comment]
ok ,I am closing this issue. Thank you very much for your quick response.
