### ISSUE TITLE
[BUG] Change theme to dark

### ISSUE THREAD

**Issue by hosttcp** [zeshuaro/flutter_theme#170]
### Platform

Web

### Steps to Reproduce

1. Open https://zeshuaro.github.io/flutter_theme in Chrome 
2. Аctivate dark theme

### Expected behaviour

The theme should be changed

### Actual behaviour

The theme not changed

### Additional Context

**Screenshots**
![scr1](https://user-images.githubusercontent.com/22972392/144849479-c0481352-fec5-44bf-8b2a-e27fd89c71de.jpg)
![scr2](https://user-images.githubusercontent.com/22972392/144849490-bfbdac53-b28c-4b9c-ba64-b788b422148c.jpg)

**Comment by zeshuaro** [comment]
Thanks @hosttcp for raising this issue. Unfortunately Flutter Theme doesn't support dark theme editing yet. This is something that I plan to work on next but I don't have a timeline on when it's going to be finished. But stay tuned for any updates in this repository 🙂
