### ISSUE TITLE
Is it possible to directly export `dart` code? This can reduce one dependency (json_theme).

### ISSUE THREAD

**Issue by xiao-cao-x** [zeshuaro/flutter_theme#70]
An additional dependency will increase the size of the APP,
Wish to add an option to export `dart` code

**Comment by zeshuaro** [comment]
> An additional dependency will increase the size of the APP

I highly doubt one additional dependency will significantly increase the size of the app.

> Wish to add an option to export dart code

Unfortunately there's no easy way to programmatically output the dart file (at least to my knowledge). If you know a way that can achieve that, feel free to share it here and I can look into it. 

However, there's also another issue where Flutter Theme will also need to be able to parse the outputted dart file for the import functionality. This is probably the main reason why I decided to output it in json format so that Flutter Theme can read it back into the app easily.

**Comment by xiao-cao-x** [comment]
> > An additional dependency will increase the size of the APP
> 
> I highly doubt one additional dependency will significantly increase the size of the app.
> 
> > Wish to add an option to export dart code
> 
> Unfortunately there's no easy way to programmatically output the dart file (at least to my knowledge). If you know a way that can achieve that, feel free to share it here and I can look into it.
> 
> However, there's also another issue where Flutter Theme will also need to be able to parse the outputted dart file for the import functionality. This is probably the main reason why I decided to output it in json format so that Flutter Theme can read it back into the app easily.

Then you can only parse the json splicing string to generate dart code.
{...} => ThemeData(...)

**Comment by xiao-cao-x** [comment]
In addition, can you add a dark style theme support option?

**Comment by xiao-cao-x** [comment]
> Then you can only parse the json splicing string to generate dart code.
> {...} => ThemeData(...)

The prerequisite for this is that the field name in json corresponds to the entity class in Dart.
For example `colorScheme`  =>  `ColorScheme`
And the parameter list should also match.

**Comment by zeshuaro** [comment]
Thanks for the suggestions but that's still additional code that I need to write to generate and parse the theme data in dart code. I would prefer to prioritise on adding complete support on all the available theming options in theme data. Dark theme support will also be looked into after this.

However, if you really want Flutter Theme to support the generation of dart code and parsing it back into the app, feel free to open a PR 🙂

**Comment by xiao-cao-x** [comment]
> 感谢您的建议，但这仍然是我需要编写的额外代码来生成和解析 dart 代码中的主题数据。我更愿意优先为主题数据中的所有可用主题选项添加完整支持。在此之后，还将研究深色主题支持。
> 
> 但是，如果你真的想让 Flutter Theme 支持生成 dart 代码并解析回应用程序，请随意打开一个 PR 🙂

![image](https://user-images.githubusercontent.com/76673990/131285589-4372cbd5-6a98-4f94-b40f-c8932b783d57.png)
I wrote some code, which can convert json data into dart code.

### theme.json:
```json
{
  "colorScheme": {
    "background": "#ffffffff",
    "brightness": "light",
    "error": "#ffb00020",
    "onBackground": "#ff000000",
    "onError": "#ffffffff",
    "onPrimary": "#ffffffff",
    "onSecondary": "#ff000000",
    "onSurface": "#ff000000",
    "primary": "#ff6200ee",
    "primaryVariant": "#ff3700b3",
    "secondary": "#ff03dac6",
    "secondaryVariant": "#ff018786",
    "surface": "#ffffffff"
  }
}
```

### Console output:
```
ThemeData(
	colorScheme:ColorScheme(
		background: const Color(0xffffffff),
		brightness: Brightness.light,
		error: const Color(0xffb00020),
		onBackground: const Color(0xff000000),
		onError: const Color(0xffffffff),
		onPrimary: const Color(0xffffffff),
		onSecondary: const Color(0xff000000),
		onSurface: const Color(0xff000000),
		primary: const Color(0xff6200ee),
		primaryVariant: const Color(0xff3700b3),
		secondary: const Color(0xff03dac6),
		secondaryVariant: const Color(0xff018786),
		surface: const Color(0xffffffff),
),);
```

### After formatting in IDEA:
![image](https://user-images.githubusercontent.com/76673990/131285784-003b9281-7014-428d-8c11-054555a17944.png)

**Comment by xiao-cao-x** [comment]
> ### theme.json:
> ```json
> {
>   "colorScheme": {
>     "background": "#ffffffff",
>     "brightness": "light",
>     "error": "#ffb00020",
>     "onBackground": "#ff000000",
>     "onError": "#ffffffff",
>     "onPrimary": "#ffffffff",
>     "onSecondary": "#ff000000",
>     "onSurface": "#ff000000",
>     "primary": "#ff6200ee",
>     "primaryVariant": "#ff3700b3",
>     "secondary": "#ff03dac6",
>     "secondaryVariant": "#ff018786",
>     "surface": "#ffffffff"
>   }
> }

But unfortunately, many field names are different from entity class names, and a lot of judgment needs to be performed, which is a tedious physical task.

> ![image](https://user-images.githubusercontent.com/76673990/131285784-003b9281-7014-428d-8c11-054555a17944.png)

**Comment by zeshuaro** [comment]
Yes I was about to comment about this, there's also all these special properties which I would imagine require additional work to handle them. And then there's the other side of things where you need to be able parse this back into the application which is basically doubling the amount of work.

**Comment by xiao-cao-x** [comment]
This json is generated by `json_theme`, I try to go to its git to find a solution.

Looking forward to your dark style theme support.

**Comment by trueshail** [comment]
@git-xiaocao would you please be able to full code snippet to convert json data into dart code for the theme?
