### ISSUE TITLE
[BUG] Export button does nothing

### ISSUE THREAD

**Issue by Mohsyn** [zeshuaro/flutter_theme#83]
**Steps To Reproduce**

1. Launch Flutter_theme on windows 10 x64
2. modify the theme
3. Click the export button

**Expected Behavior**

json output should be created

**Actual behaviour**

nothing happens

**Comment by zeshuaro** [comment]
Thanks for reporting this bug. Like I mentioned on the README, I don't have a Windows machine so I can't really debug and test the app for Windows. Please use the web version for now, I'll see what I can do with debugging the Windows app.

**Comment by zeshuaro** [comment]
@Mohsyn I've just released `v0.0.1-dev.8` to fix this issue. Feel free to reopen this issue if the it's still not working.
